
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _DB_AG__Online_Kredit.BusinessLogic
{

using System;
    using System.Collections.Generic;
    
public partial class Arbeitgeber
{

    public int ID { get; set; }

    public string Firma { get; set; }

    public int FKBeschaeftigungsArt { get; set; }

    public Nullable<int> FKBranche { get; set; }

    public Nullable<System.DateTime> BeschaeftigtSeit { get; set; }



    public virtual BeschaeftigungsArt BeschaeftigungsArt { get; set; }

    public virtual Branche Branche { get; set; }

    public virtual Kunde Kunde { get; set; }

}

}
