
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _DB_AG__Online_Kredit.BusinessLogic
{

using System;
    using System.Collections.Generic;
    
public partial class BeschaeftigungsArt
{

    public BeschaeftigungsArt()
    {

        this.AlleArbeitgeber = new HashSet<Arbeitgeber>();

    }


    public int ID { get; set; }

    public string Bezeichnung { get; set; }



    public virtual ICollection<Arbeitgeber> AlleArbeitgeber { get; set; }

}

}
