
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _DB_AG__Online_Kredit.BusinessLogic
{

using System;
    using System.Collections.Generic;
    
public partial class KreditWunsch
{

    public int ID { get; set; }

    public decimal Betrag { get; set; }

    public short Laufzeit { get; set; }

    public bool Bewilligt { get; set; }



    public virtual Kunde Kunde { get; set; }

}

}
