
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _DB_AG__Online_Kredit.BusinessLogic
{

using System;
    using System.Collections.Generic;
    
public partial class Land
{

    public Land()
    {

        this.AlleKunden_Staatsangehörigkeit = new HashSet<Kunde>();

        this.Ort = new HashSet<Ort>();

    }


    public string ID { get; set; }

    public string Bezeichnung { get; set; }



    public virtual ICollection<Kunde> AlleKunden_Staatsangehörigkeit { get; set; }

    public virtual ICollection<Ort> Ort { get; set; }

}

}
