
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace _DB_AG__Online_Kredit.BusinessLogic
{

using System;
    using System.Collections.Generic;
    
public partial class Ort
{

    public Ort()
    {

        this.AlleKontaktDaten = new HashSet<KontaktDaten>();

    }


    public int ID { get; set; }

    public string PLZ { get; set; }

    public string FKLand { get; set; }

    public string Bezeichnung { get; set; }



    public virtual ICollection<KontaktDaten> AlleKontaktDaten { get; set; }

    public virtual Land Land { get; set; }

}

}
